### ISSUE TITLE
reset mime-types

### ISSUE THREAD

**Issue by dotnetCarpenter** [broofa/node-mime#124]
I'm writing unit tests for [ecstatic's new custom mime-type feature](https://github.com/jfhbrook/node-ecstatic/pull/143) and can't do a proper _teardown_ between tests due to a number of reasons. But the main one, that stops me right now, is that `mime` doesn't have  a _reset-mime-types_ function.

I can do `mime = new mime.Mime();` but that doesn't load the default types.

``` js
// Define built-in types
mime.define(require('./types.json'));

// Default type
mime.default_type = mime.lookup('bin');
```

Could you add a _reset-mime-types_ function, please?

**Comment by Hypercubed** [comment]
Can be solved by #129

**Comment by dotnetCarpenter** [comment]
@Hypercubed you mean I should use https://github.com/Hypercubed/node-mime?

**Comment by Hypercubed** [comment]
Your use case (feel free to correct me) is that you would like an mime lookup instance that includes the default types, expand the default types using `mime.define`, then later be able to create a new instance with only the default types not your additional defintions.

The main node-mime fork has two options:
1) Use the default instance using `var mime = require('mime')`.
2) Create a new instance `var mime = new require('mime').Mime()` that does not include the default mime types.

This is an all or noting approach.  # 1 includes the default types but since this is a singleton and addition definitions are global and cannot be reset.  # 2 is a instance that you can expand with your types, destroy when done, then create a new instance.   However, this instance lacks the default types.

My suggestion in `https://github.com/Hypercubed/node-mime` is to separate the db from the API.  So you can do this:

```
var MimeLookup = require('mime-lookup');                           // load the class constructor
var mime = new MimeLookup (require('mime-db'));             // load the default types.
```

Teardown between tests would mean creating a new instance.  I will likely make my version of node-mime a separate module (perhaps `mime-lookup`) but I am waiting for feedback from @broofa .

**Comment by broofa** [comment]
I know it's been a while.  I like this idea for v2.  I'll figure something out for v2.

**Comment by broofa** [comment]
v2 is out.  [index.js](https://github.com/broofa/node-mime/blob/master/index.js) shows how to build the default `mime` object.  Should be pretty straigh-forward to address this in your tests.

**Comment by broofa** [comment]
My apologies. `index.js` is misleading as it's using local paths to the types files.  To create your own fresh mime instance with all of the type definitions:
```
const Mime = require('mime/Mime');
const mime = new Mime(require('mime/types/standard'), require('mime/types/other'));
```

**Comment by perrosen** [comment]
Just a note for anyone else coming across this issue. I needed to add the .json extension for webpack to find the types.
