### ISSUE TITLE
The extension for video/quicktime should map to .mov, not .qt

### ISSUE THREAD

**Issue by timcosta** [broofa/node-mime#164]
.qt is a deprecated extension, and while this was once accurate it means that looking up the mime for `.mov` and then getting the extension for the returned `video/quicktime` results in mismatched extensions.

**Comment by broofa** [comment]
Finally got a chance to look into this.

The problem is that the `qt` extension is named first in both `[mime-db](https://github.com/jshttp/mime-db/blob/master/db.json#L6746)` and [Apache mime types file](https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types).

This is where `mime-db` draws it's type info from, and it maintains the extension ordering.  Both this module and the `mime-types` module prefer the first extension when mapping type -> extension.   And I suspect neither I nor the `mime-types` authors are interested in special casing this in our code.  The solution really needs to be in either `mime-db` or Apache's types file.

So... I'd suggest you file an issue with `mime-db` to that affect.  You might also file a bug with the Apache project, but I don't know how willing they'll be to change there.
