### ISSUE TITLE
fs.readFileSync is not a function

### ISSUE THREAD

**Issue by Fayde** [broofa/node-mime#165]
Recently updating my angular dependencies to angular cli 1.1.1 and related packages to 4.2.2 and this is being thrown from mime.js, any ideas because i'm lost

**Comment by broofa** [comment]
I assume this is browser-side code, where the `fs` module is just shimmed with an empty object (or whatever).

That error is probably coming from `mime`'s legacy support for the `mime#load()` method, [here](https://github.com/broofa/node-mime/blob/master/mime.js#L50).  I left that method in when I switched from reading the Apache configuration file to, instead, use the mime-db dataset (as types.json).  This code was never really intended to be run in the browser, but apparently some module somewhere is trying to call into it...?

Easy way to identify the culprit is to edit your `node_modules/mime/mime.js` file and throw a `console.trace()` statement in there and see what shows up.

**Comment by aarohmankad** [comment]
Can you think of any fix for this? I need to use the `intimidate` package for uploading Buffer's to S3, and they require `mime`.

I'm also getting the error, and can't seem to find anywhere where `mime#load()` is called. I do see placed where `mime#lookup()` is called. Is `lookup()` vulnerable to the same issue?

**Comment by aarohmankad** [comment]
Okay so it seems `mime` itself is calling `mime#load()`. Is there any alternative method of writing the following piece of code that will allow `mime` to run in the browser?

![image](https://user-images.githubusercontent.com/3311321/29048202-4c33ccd4-7b84-11e7-9e42-8e1f0bdcea22.png)

**Comment by broofa** [comment]
@aarohmankad try doing `npm install mime@latest`.  `intimidate` depends on "`mime@^1.2.9`".  Forcing npm to install the latest version (which doesn't call `mime.load()` during initialization) may fix this issue.

**Comment by aarohmankad** [comment]
It does fix the issue! I submitted a PR to `intimidate` to upgrade the mime version. Don't think it will be merged anytime soon though. (Last commit was 2015.)

**Comment by broofa** [comment]
`load()` removed in v2
