### ISSUE TITLE
UTF-8 charset by default on "text/html"

### ISSUE THREAD

**Issue by Sterpa** [broofa/node-mime#174]
Hi,
In the 21st century, UTF-8 became de facto the standard for www.
In order to not overwrite thousands of http-server, it's enough to change "text/html" to "text/html;charset=UTF-8" in mime-types by default.
This does not change the work of old html-documents in any way, but instantly includes the correct display of many-many new languages.

```
"text/html;charset=UTF-8": {
    "source": "iana",
    "compressible": true,
    "extensions": ["html","htm","shtml"]
}
```

**Comment by jiankafei** [comment]
@Sterpa Maybe, you should submit this issue to jshttp/mime-db.

**Comment by broofa** [comment]
@Sterpa I'm afraid I'm having trouble with the language barrier.  I don't really know what it is you're asking for here.  As of 2.x, I've dropped the `charset` api in this module because, frankly, it was shit code.  It was ad hoc logic added years ago with no real thought or consideration, and it never received much love.  (Basically if a type started with "text", then it returned the `UTF-8`).

I'm open to adding support for charsets back in - probably as a `getContentType()` method, but I'd like a more canonical approach... and I haven't had time to sit down and figure out what that is.

FWIW, The `mime-types` module has the `contentType` method, which may be what you're looking for in the interim.
