### ISSUE TITLE
mime.getExtensions('text/xml') is null

### ISSUE THREAD

**Issue by valeriangalliat** [broofa/node-mime#180]
Version 2.0.3.

`types/standard.json` have `"text/xml":[]`.

This is caused by [this line](https://github.com/broofa/node-mime/blob/930187b8017a4c07322653481cc801e485701fde/src/build.js#L75).

I understand the idea of preferring `application/...` types over `text/...` but is it the expected behaviour that we can't reverse the proper extension from let's say `text/xml` because `application/xml` also exists?

Thank you!

**Comment by broofa** [comment]
Hmm... good point.  The goal here was to eliminate the ambiguity around the more common problem of resolving an extension to a mime-type.  Breaking the ability to map less-preferred types to an extension was an unintentional side-effect of that.

Any chance you'd be willing to put together a PR?  I think it would be okay to keep these sorts of mappings, as long as the extension -> type mapping always resolves to the highest scoring type (per the `getScore()` method).

**Comment by valeriangalliat** [comment]
@broofa I don't see a way to do that without breaking the format of `typeMap`, do you think `typeMap` could have the following schema?

```json
{
  "types": {
    "application/xml": ["xml"],
    "text/xml": ["xml"]
  },
  "extensions": {
    "xml": ["application/xml", "text/xml"]
  }
}
```

Also what do you think of adding `getTypes` and `getExtensions` methods that would return an array of matching types or matching extensions (in priority order)?

**Comment by broofa** [comment]
@valeriangalliat 'Been thinking about this and the least impactful solution I can come up with is to change the build step such that, instead of filtering out the conflicting extensions, it prefixes the non-default extensions with a `*` (or other appropriate character).  E.g. 
```
{
  ...
  "application/xml": ["xml"],
  "text/xml": ["*xml"],
  ...
}
```
Then have the `Mime` class treat the non-default entries appropriately in the `define()` method.  It's a bit of a hack, but it'd be backward compatible with the current code.

**Comment by valeriangalliat** [comment]
Amazing, thank you!
