### ISSUE TITLE
node-mime and webpack

### ISSUE THREAD

**Issue by tmaslen** [broofa/node-mime#188]
Hi Broofa,

This is more a question than an issue. I've tried to understand by reading the other issues regarding webpack how to concatenate node-mime into a compiled source using webpack but I'm having problems with it.

I'm getting the error...

```
ENOENT: no such file or directory, open '/var/task/node_modules/node-bitlyapi/node_modules/mime/types/mime.types'
```

... when using a node module that uses node-mime.

I'm not using webpack in a standard way, so its hard for me to create a simple example of it not working. I think the reason why I'm getting the error is that webpack is statically analysing node-mime to trace dependencies, and because the `mime.types` file is added in using this line `content = fs.readFileSync(file, 'ascii')` the analyser is unable to follow it to the intended file.

Do you know what I have to tell webpack in order for it to successfully trace all the dependencies in your project?

Thanks, and apologies if this is a dumb question.

/t

**Comment by broofa** [comment]
This is caused by a dependency on an old version of this module. (I removed `mime.types` and `fs.readFileAsync` a couple years ago.)  Specifically, I believe it's because [`node-bitlyapi` is depending on an old version of request](http://npm.broofa.com/?q=node-bitlyapi) which, in turn, depends on `mime@1.2.11`.

Fix is to get `node-bitlyapi` project to update their dependencies.
