### ISSUE TITLE
error-cannot-find-module-mime  

### ISSUE THREAD

**Issue by ffang0715** [broofa/node-mime#189]
### If you have an issue with a specific extension or type

Locate the definition for your extension/type in the [db.json file](https://github.com/jshttp/mime-db/blob/master/db.json) in the `mime-db` project.  Does it look right?

  [ ] No. [File a `mime-db` issue](https://github.com/jshttp/mime-db/issues/new).
  [ X] Yes: Go ahead and submit your issue/PR here and I'll look into it.

I was pushing the code to heroku and there seems to be a problem with the module?

I haven't tried it, but possibly the require /Mime should be lowercase? 

I installed mime with -save -g.
The code works fine on local host... so I'm really not sure what the problem is.

Anyone can help?

![26781346_10213548159752006_109668327_o](https://user-images.githubusercontent.com/27721801/34855926-5aaea5fc-f77d-11e7-8812-a1ab1c91e635.png)

**Comment by broofa** [comment]
Looks like it's complaining about [this import](https://github.com/broofa/node-mime/blob/master/index.js#L3), but that doesn't really make sense since `Mime.js` is (or, at least, should be) in the same directory as `index.js`.  Can you `ls /App/node_modules/mime/index.js`

If you're pushing this to Heroku, why are you installing with `-g`?  That seems... wrong. (But I'm not a Heroku guy so not sure how that side of things works.)

**Comment by ffang0715** [comment]
![image](https://user-images.githubusercontent.com/27721801/34858238-1a7ca832-f78a-11e7-9141-5564b98a46e4.png)

Hey @broofa 

Thanks for the reply.

Yes, i can ls that file path

Here's a screen cap

**Comment by broofa** [comment]
Sorry, I meant `ls /app/node_modules/mime`.  Just to insure `Mime.js` is alongside `index.js`.  You could also try `cd /app; node -e "console.log(require('mime'))"`.  That should output the mime module.

This is probably a configuration issue of some sort.  I'm afraid I won't be much help beyond this so you'll have to debug on your side.  Please followup here when you figure out the problem (and on that SO page as well) so others can benefit.

P.S.  Screenshots of code are less than ideal since they can be hard to read, can't search, can't copy/paste text.  It's better to just copy/paste output as code-blocks (```-blocks) or gists.

**Comment by ffang0715** [comment]
@broofa 

I'm not really sure... but I noticed that when I npm install mime, the mime.js  is "lowercase" while the required format is uppercase Mime.js?

I am running on mac locally and i think mac isn't too case sensitive, but heroku is running on Linux, which IS case sensitive.

I'm still trying to figure out how I can test the case sensitivity issue.

I read about this here.
https://stackoverflow.com/questions/19341975/heroku-node-cannot-find-module-error

the top rated solution

**Comment by broofa** [comment]
[FWIW, [I'm aware of](https://github.com/broofa/checkForModuleDuplicates) mac casing issues.] But if `/app/node_modules/mime/Mime.js` exists for you I don't think that's the problem here (but I could always be wrong).

What happens when you run the command in my previous comment?

**Comment by ffang0715** [comment]
@broofa     

nope, Capital Mime.js doesn't exist, 

I cd'ed into the folder and ls'ed.

The result was mime.js lowercase

and I didn't make it lower case myself, all I did was npm install

After I changed it to uppercase and git push, the error disappeared!

**Comment by broofa** [comment]
Hmm... had you upgraded from `mime@v1.x` at some point?  Version 1 of this module had a `mime.js` file, but version 2 has `Mime.js`.  I think I've seen cases where case-agnostic filesystems keep whatever the original casing is.

You might try blowing away your node_modues dir and re-installing to see if that would also fix the problem.

Regardless, since the problem went away I'm going to close this out.

**Comment by swaaap-nil** [comment]
I am using NestJS and the solution for me was to add ` "typeRoots": [],`
in `tsconfig.json`. I solved it accidentally and don't know why this works.
